# Creación de un DaemonSet
# Un DaemonSet és una forma de Deployear un Pod, pero va estar Deployado en todos los nodos
# Va crear un solo Pod en cada Nodo
# No tiene réplicas porque depende de la cantidad de nodos que tengamos
# Si tenemos 3 nodos, vamos a tener 3 Pods y cada uno de esos nodos va tener una réplica del Pod

apiVersion: apps/v1
kind: DaemonSet # Tipo de recurso
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: MI_VARIABLE
          value: "cristian"
        - name: MI_OTRA_VARIABLE
          value: "fernández"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 80