# Creación de un StateFulSet
# És otra forma de crear Pods que aparte de correr cómo otro Deployment tienen un volúmen.
# Un volúmenr és un directorio o un disco que va estar atado a ese Pod y ese Pod va ser siempre atado a ese disco.
# Puede servir para una base de datos, ya que nunca vamos a perder los datos del disco. Ya que si el Pod muere los datos no se pierden.

apiVersion: apps/v1
kind: StatefulSet # Tipo de recurso
metadata:
  name: my-csi-app-set
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 1 # Indicamos que sólo queremos un Pod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: my-frontend
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts: # Montamos un volúmen
        - mountPath: "/data" # Lo montamos en /data
          name: csi-pvc
  volumeClaimTemplates: # Declaramos el volúmen
  - metadata:
      name: csi-pvc
    spec:
      accessModes: # Indicamos los modos de acceso al almacenamiento.
      - ReadWriteOnce # Que sea de Lectura/Escritura
      resources: # Definimos los recursos
        requests: # Especificamos la cantidad de almacenamiento solicitada.
          storage: 5Gi
      storageClassName: do-block-storage