# Crear recurso ConfigMap
# ConfigMap permite almacenar datos en un archivo aparte y luego referenciarlo a los Pods.

apiVersion: v1
kind: ConfigMap # Tipo de recurso ConfigMap
metadata:
  name: game-demo # Nombre del recurso
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true