# Crear recurso Secret
# Es similar a ConfigMap, pero se utiliza específicamente para almacenar información sensible, como contraseñas, claves de API.
# Todos los datos se tienen que poner codificados en Base64, y los Pods pueden leerlos (Nosotros no porque esta codificado).

apiVersion: v1
kind: Secret # Tipo de recurso (Secret)
metadata:
  name: db-credentials # Nombre del recurso
type: Opaque
data: # Definimos los datos codificados en Base64
  username: YWRtaW4=
  password: c3VwM3JwYXNzdzByZAo=

# Esto se puede crear a mano:
# kubectl create secret generic db-credentials --from-literal=username=admin --from-literal=password=sup3rpassw0rd
# Docs: https://kubernetes.io/es/docs/concepts/configuration/secret/