# Crear Pod y referenciar datos de Secret
# Decodifica los datos una vez se crea el Pod

apiVersion: v1
kind: Pod # Tipo de recurso (Pod)
metadata:
  name: nginx # Nombre del recurso
spec:
  containers: # Especificamos el contenedor
  - name: nginx
    image: nginx:alpine
    env:
    - name: MI_VARIABLE # Creamos una variable de ejemplo
      value: "pelado"
    - name: MYSQL_USER # Creamos una variable
      valueFrom:
        secretKeyRef:
          name: db-credentials # El Secret desde donde vienen los valores
          key: username # La key que vamos a usar
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    ports:
    - containerPort: 80 # Escucha desde el puerto 80